apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-labels
  labels: 
    environment: dev 
    app: http-server
spec:
  containers:
  - name: app-kuber-container
    image: alekseevdm/my-nginx-app:latest
    ports:
    - containerPort: 443
