apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 443         # порт внутри кластера
      targetPort: 443   # порт контейнера
      nodePort: 32222   # желаемый порт на узле
  type: NodePort
