apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 2
  selector:
    app: http-server
  template:
    metadata:
      name: kuber-app
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: alekseevdm/my-nginx-app:latest
        ports:
        - containerPort: 443